#############################################################################
# Makefile for building: BMBCropper
# Generated by qmake (2.01a) (Qt 4.7.3) on: Wed Nov 30 14:53:01 2016
# Project:  BMBCropper.pro
# Template: app
# Command: /opt/qt-marlin2/bin/qmake -spec ../../../qt-marlin2/mkspecs/linux-g++ CONFIG+=debug -o Makefile BMBCropper.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -Wno-trigraphs -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -Wno-trigraphs -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../qt-marlin2/mkspecs/linux-g++ -I. -I../../../qt-marlin2/include/QtCore -I../../../qt-marlin2/include/QtGui -I../../../qt-marlin2/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qt-marlin2/lib
LIBS          = $(SUBLIBS)  -L/opt/qt-marlin2/lib -lQtGui -L/opt/qt-marlin2/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qt-marlin2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		framegenerator.cpp \
		weddingframegenerator.cpp \
		reportageframegenerator.cpp \
		frameoption.cpp \
		abstractoption.cpp moc_mainwindow.cpp \
		moc_framegenerator.cpp \
		moc_weddingframegenerator.cpp \
		moc_reportageframegenerator.cpp \
		moc_frameoption.cpp \
		moc_abstractoption.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		framegenerator.o \
		weddingframegenerator.o \
		reportageframegenerator.o \
		frameoption.o \
		abstractoption.o \
		moc_mainwindow.o \
		moc_framegenerator.o \
		moc_weddingframegenerator.o \
		moc_reportageframegenerator.o \
		moc_frameoption.o \
		moc_abstractoption.o \
		qrc_resources.o
DIST          = ../../../qt-marlin2/mkspecs/common/g++.conf \
		../../../qt-marlin2/mkspecs/common/unix.conf \
		../../../qt-marlin2/mkspecs/common/linux.conf \
		../../../qt-marlin2/mkspecs/qconfig.pri \
		../../../qt-marlin2/mkspecs/modules/qt_webkit_version.pri \
		../../../qt-marlin2/mkspecs/features/qt_functions.prf \
		../../../qt-marlin2/mkspecs/features/qt_config.prf \
		../../../qt-marlin2/mkspecs/features/exclusive_builds.prf \
		../../../qt-marlin2/mkspecs/features/default_pre.prf \
		../../../qt-marlin2/mkspecs/features/debug.prf \
		../../../qt-marlin2/mkspecs/features/default_post.prf \
		../../../qt-marlin2/mkspecs/features/warn_on.prf \
		../../../qt-marlin2/mkspecs/features/qt.prf \
		../../../qt-marlin2/mkspecs/features/unix/thread.prf \
		../../../qt-marlin2/mkspecs/features/moc.prf \
		../../../qt-marlin2/mkspecs/features/resources.prf \
		../../../qt-marlin2/mkspecs/features/uic.prf \
		../../../qt-marlin2/mkspecs/features/yacc.prf \
		../../../qt-marlin2/mkspecs/features/lex.prf \
		../../../qt-marlin2/mkspecs/features/include_source_dir.prf \
		BMBCropper.pro
QMAKE_TARGET  = BMBCropper
DESTDIR       = 
TARGET        = BMBCropper

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BMBCropper.pro  ../../../qt-marlin2/mkspecs/linux-g++/qmake.conf ../../../qt-marlin2/mkspecs/common/g++.conf \
		../../../qt-marlin2/mkspecs/common/unix.conf \
		../../../qt-marlin2/mkspecs/common/linux.conf \
		../../../qt-marlin2/mkspecs/qconfig.pri \
		../../../qt-marlin2/mkspecs/modules/qt_webkit_version.pri \
		../../../qt-marlin2/mkspecs/features/qt_functions.prf \
		../../../qt-marlin2/mkspecs/features/qt_config.prf \
		../../../qt-marlin2/mkspecs/features/exclusive_builds.prf \
		../../../qt-marlin2/mkspecs/features/default_pre.prf \
		../../../qt-marlin2/mkspecs/features/debug.prf \
		../../../qt-marlin2/mkspecs/features/default_post.prf \
		../../../qt-marlin2/mkspecs/features/warn_on.prf \
		../../../qt-marlin2/mkspecs/features/qt.prf \
		../../../qt-marlin2/mkspecs/features/unix/thread.prf \
		../../../qt-marlin2/mkspecs/features/moc.prf \
		../../../qt-marlin2/mkspecs/features/resources.prf \
		../../../qt-marlin2/mkspecs/features/uic.prf \
		../../../qt-marlin2/mkspecs/features/yacc.prf \
		../../../qt-marlin2/mkspecs/features/lex.prf \
		../../../qt-marlin2/mkspecs/features/include_source_dir.prf \
		/opt/qt-marlin2/lib/libQtGui.prl \
		/opt/qt-marlin2/lib/libQtCore.prl
	$(QMAKE) -spec ../../../qt-marlin2/mkspecs/linux-g++ CONFIG+=debug -o Makefile BMBCropper.pro
../../../qt-marlin2/mkspecs/common/g++.conf:
../../../qt-marlin2/mkspecs/common/unix.conf:
../../../qt-marlin2/mkspecs/common/linux.conf:
../../../qt-marlin2/mkspecs/qconfig.pri:
../../../qt-marlin2/mkspecs/modules/qt_webkit_version.pri:
../../../qt-marlin2/mkspecs/features/qt_functions.prf:
../../../qt-marlin2/mkspecs/features/qt_config.prf:
../../../qt-marlin2/mkspecs/features/exclusive_builds.prf:
../../../qt-marlin2/mkspecs/features/default_pre.prf:
../../../qt-marlin2/mkspecs/features/debug.prf:
../../../qt-marlin2/mkspecs/features/default_post.prf:
../../../qt-marlin2/mkspecs/features/warn_on.prf:
../../../qt-marlin2/mkspecs/features/qt.prf:
../../../qt-marlin2/mkspecs/features/unix/thread.prf:
../../../qt-marlin2/mkspecs/features/moc.prf:
../../../qt-marlin2/mkspecs/features/resources.prf:
../../../qt-marlin2/mkspecs/features/uic.prf:
../../../qt-marlin2/mkspecs/features/yacc.prf:
../../../qt-marlin2/mkspecs/features/lex.prf:
../../../qt-marlin2/mkspecs/features/include_source_dir.prf:
/opt/qt-marlin2/lib/libQtGui.prl:
/opt/qt-marlin2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../qt-marlin2/mkspecs/linux-g++ CONFIG+=debug -o Makefile BMBCropper.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/BMBCropper1.0.0 || $(MKDIR) .tmp/BMBCropper1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/BMBCropper1.0.0/ && $(COPY_FILE) --parents mainwindow.h framegenerator.h weddingframegenerator.h reportageframegenerator.h frameoption.h abstractoption.h .tmp/BMBCropper1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/BMBCropper1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp framegenerator.cpp weddingframegenerator.cpp reportageframegenerator.cpp frameoption.cpp abstractoption.cpp .tmp/BMBCropper1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/BMBCropper1.0.0/ && (cd `dirname .tmp/BMBCropper1.0.0` && $(TAR) BMBCropper1.0.0.tar BMBCropper1.0.0 && $(COMPRESS) BMBCropper1.0.0.tar) && $(MOVE) `dirname .tmp/BMBCropper1.0.0`/BMBCropper1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/BMBCropper1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_framegenerator.cpp moc_weddingframegenerator.cpp moc_reportageframegenerator.cpp moc_frameoption.cpp moc_abstractoption.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_framegenerator.cpp moc_weddingframegenerator.cpp moc_reportageframegenerator.cpp moc_frameoption.cpp moc_abstractoption.cpp
moc_mainwindow.cpp: framegenerator.h \
		frameoption.h \
		abstractoption.h \
		mainwindow.h
	/opt/qt-marlin2/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_framegenerator.cpp: frameoption.h \
		abstractoption.h \
		framegenerator.h
	/opt/qt-marlin2/bin/moc $(DEFINES) $(INCPATH) framegenerator.h -o moc_framegenerator.cpp

moc_weddingframegenerator.cpp: framegenerator.h \
		frameoption.h \
		abstractoption.h \
		weddingframegenerator.h
	/opt/qt-marlin2/bin/moc $(DEFINES) $(INCPATH) weddingframegenerator.h -o moc_weddingframegenerator.cpp

moc_reportageframegenerator.cpp: framegenerator.h \
		frameoption.h \
		abstractoption.h \
		reportageframegenerator.h
	/opt/qt-marlin2/bin/moc $(DEFINES) $(INCPATH) reportageframegenerator.h -o moc_reportageframegenerator.cpp

moc_frameoption.cpp: abstractoption.h \
		frameoption.h
	/opt/qt-marlin2/bin/moc $(DEFINES) $(INCPATH) frameoption.h -o moc_frameoption.cpp

moc_abstractoption.cpp: abstractoption.h
	/opt/qt-marlin2/bin/moc $(DEFINES) $(INCPATH) abstractoption.h -o moc_abstractoption.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		open-folder \
		close \
		play \
		bmb-logo \
		bmb-gray.png \
		bmb.png
	/opt/qt-marlin2/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/qt-marlin2/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		framegenerator.h \
		frameoption.h \
		abstractoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp framegenerator.h \
		frameoption.h \
		abstractoption.h \
		mainwindow.h \
		reportageframegenerator.h \
		ui_mainwindow.h \
		weddingframegenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

framegenerator.o: framegenerator.cpp framegenerator.h \
		frameoption.h \
		abstractoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o framegenerator.o framegenerator.cpp

weddingframegenerator.o: weddingframegenerator.cpp weddingframegenerator.h \
		framegenerator.h \
		frameoption.h \
		abstractoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o weddingframegenerator.o weddingframegenerator.cpp

reportageframegenerator.o: reportageframegenerator.cpp reportageframegenerator.h \
		framegenerator.h \
		frameoption.h \
		abstractoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reportageframegenerator.o reportageframegenerator.cpp

frameoption.o: frameoption.cpp frameoption.h \
		abstractoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frameoption.o frameoption.cpp

abstractoption.o: abstractoption.cpp abstractoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstractoption.o abstractoption.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_framegenerator.o: moc_framegenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_framegenerator.o moc_framegenerator.cpp

moc_weddingframegenerator.o: moc_weddingframegenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_weddingframegenerator.o moc_weddingframegenerator.cpp

moc_reportageframegenerator.o: moc_reportageframegenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reportageframegenerator.o moc_reportageframegenerator.cpp

moc_frameoption.o: moc_frameoption.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frameoption.o moc_frameoption.cpp

moc_abstractoption.o: moc_abstractoption.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_abstractoption.o moc_abstractoption.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

